version: "3"

services: 
      
  redis:
    image: redis:latest
    container_name: hepsiredis
    command: redis-server --requirepass hepsipassword
    ports:
     - 7331:6379
    networks:
     - hepsi-network
    

  hepsimongo:
    image: mongo:latest
    container_name: hepsimongo
    ports: 
     - 27017:27017
  
networks: 
  logging-network:
    driver: bridge
  hepsi-network:
    driver: bridge
    
 
      
volumes:
  elasticsearch-data:
  portainer_data: